export const Books = [
    {
      id: 1,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      publicationDate: "1960-07-11",
      category:"Fiction",
      isFamous:true,
      rating: 4.9,
      coverImage: "../public/images/first.jpg",
      description: "A novel set in the 1930s about racial injustice and moral growth in a small Southern town.",
      pages:"209",
    },
    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      publicationDate: "1949-06-08",
      category:"Non-Fiction",
      isFamous:false,
      rating: 4.1,
      coverImage: "../public/images/second.jpg",
      description: "A dystopian novel that explores themes of totalitarianism, surveillance, and individuality.",
      pages:"180",
    },
    {
      id: 3,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      publicationDate: "1925-04-10",
      category:"Sci-Fi",
      isFamous:true,
      rating: 4.6,
      coverImage: "../public/images/third.jpg",
      description: "A classic novel about the American Dream and the disillusionment of the Jazz Age.",
      pages:"210",
    },
    {
      id: 4,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      publicationDate: "1813-01-28",
      category:"Fiction",
      isFamous:false,
      rating: 4.4,
      coverImage: "../public/images/fourth.jpg",
      description: "A romantic novel that critiques the societal expectations of 19th-century England.",
      pages:"195",
    },
    {
      id: 5,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      publicationDate: "1951-07-16",
      category:"Non-Fiction",
      isFamous:true,
      rating: 4.5,
      coverImage: "../public/images/fifth.jpg",
      description: "A story about teenage alienation and rebellion, narrated by the iconic Holden Caulfield.",
      pages:"222",
    },
    {
      id: 6,
      title: "Moby-Dick",
      author: "Herman Melville",
      publicationDate: "1851-10-18",
      category:"Sci-Fi",
      isFamous:false,
      rating: "4.0",
      coverImage: "../public/images/sixth.jpg",
      description: "An epic tale of obsession and revenge as Captain Ahab hunts the white whale.",
      pages:"275",
    },
    {
      id: 7,
      title: "Brave New World",
      author: "Aldous Huxley",
      publicationDate: "1932-08-18",
      category:"Fiction",
      isFamous:true,
      rating: 4.8,
      coverImage: "../public/images/seventh.jpg",
      description: "A futuristic society where technology controls every aspect of human life.",
      pages:"250",
    },
    {
      id: 8,
      title: "Jane Eyre",
      author: "Charlotte Brontë",
      publicationDate: "1847-10-16",
      category:"Non-Fiction",
      isFamous:false,
      rating: 4.3,
      coverImage: "../public/images/eighth.jpg",
      description: "A gothic novel exploring themes of love, independence, and morality.",
      pages:"288",
    },
    {
      id: 9,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      publicationDate: "1937-09-21",
      category:"Sci-Fi",
      isFamous:true,
      rating: 4.7,
      coverImage: "../public/images/ninth.jpg",
      description: "A fantasy adventure about a hobbit named Bilbo Baggins and his journey to reclaim treasure.",
      pages:"308",
    },
    {
      id: 10,
      title: "The Odyssey",
      author: "Homer",
      publicationDate: "800-01-01",
      category:"Fiction",
      isFamous:false,
      rating: 3.9,
      coverImage: "../public/images/tenth.jpg",
      description: "An epic poem recounting the adventures of Odysseus as he returns home from the Trojan War.",
      pages:"259",
    },
    {
      id: 11,
      title: "The Alchemist",
      author: "Paulo Coelho",
      publicationDate: "1988-04-15",
      category: "Fiction",
      isFamous: true,
      rating: 4.7,
      coverImage: "../public/images/eleventh.jpg",
      description: "A philosophical novel about following one's dreams and destiny.",
      pages: "197",
    },
    {
      id: 12,
      title: "Sapiens: A Brief History of Humankind",
      author: "Yuval Noah Harari",
      publicationDate: "2011-06-04",
      category: "Non-Fiction",
      isFamous: false,
      rating: 4.8,
      coverImage: "../public/images/twelfth.png",
      description: "An exploration of human history and evolution from ancient times to the modern era.",
      pages: "412",
    },
    {
      id: 13,
      title: "Dune",
      author: "Frank Herbert",
      publicationDate: "1965-08-01",
      category: "Sci-Fi",
      isFamous: true,
      rating: 4.6,
      coverImage: "../public/images/thirteenth.jpg",
      description: "A science fiction epic set in a desert world with political intrigue and adventure.",
      pages: "412",
    },
    {
      id: 14,
      title: "Frankenstein",
      author: "Mary Shelley",
      publicationDate: "1818-01-01",
      category: "Sci-Fi",
      isFamous: false,
      rating: 4.3,
      coverImage: "../public/images/fourteenth.jpg",
      description: "A classic Gothic horror novel about a scientist who creates a living being.",
      pages: "280",
    },
    {
      id: 15,
      title: "The Silent Patient",
      author: "Alex Michaelides",
      publicationDate: "2019-02-05",
      category: "Fiction",
      isFamous: true,
      rating: 4.5,
      coverImage: "../public/images/fifteenth.jpg",
      description: "A psychological thriller about a woman who stops speaking after a violent crime.",
      pages: "336",
    },
    {
      id: 16,
      title: "Educated",
      author: "Tara Westover",
      publicationDate: "2018-02-20",
      category: "Non-Fiction",
      isFamous: false,
      rating: 4.7,
      coverImage: "../public/images/sixteenth.jpg",
      description: "A memoir about a woman who grows up in a survivalist family and pursues education.",
      pages: "334",
    },
    {
      id: 17,
      title: "Neuromancer",
      author: "William Gibson",
      publicationDate: "1984-07-01",
      category: "Sci-Fi",
      isFamous: true,
      rating: 4.2,
      coverImage: "../public/images/seventeenth.jpg",
      description: "A cyberpunk classic that explores artificial intelligence and virtual reality.",
      pages: "271",
    },
    {
      id: 18,
      title: "The Road",
      author: "Cormac McCarthy",
      publicationDate: "2006-09-26",
      category: "Fiction",
      isFamous: false,
      rating: 4.4,
      coverImage: "../public/images/eighteenth.jpg",
      description: "A post-apocalyptic novel about a father and son’s journey for survival.",
      pages: "287",
    },
    {
      id: 19,
      title: "Atomic Habits",
      author: "James Clear",
      publicationDate: "2018-10-16",
      category: "Non-Fiction",
      isFamous: true,
      rating: 4.8,
      coverImage: "../public/images/nineteenth.jpg",
      description: "A self-improvement book about building good habits and breaking bad ones.",
      pages: "320",
    },
    {
      id: 20,
      title: "Hyperion",
      author: "Dan Simmons",
      publicationDate: "1989-05-26",
      category: "Sci-Fi",
      isFamous: false,
      rating: 4.5,
      coverImage: "../public/images/twentieth.jpg",
      description: "A space opera with interwoven stories of pilgrims traveling to the planet Hyperion.",
      pages: "482",
    }
  ];
  
 
  